version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm i
      - 'aws s3 cp s3://aha-secrets/service-account.json ./src/modules/auth/.'
      - ls -la src/modules/auth
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -la
      - pwd
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages
# used only for building and testing.
artifacts:
  files:
    - '**/*'
