export const RABBIT_CONNECTION = 'RABBIT_CONNECTION';
export const SQS_OPTIONS = 'SQS_OPTIONS';
export const QUEUE_REPO_INJECT = 'QUEUE_REPO_INJECT';
export const POSTGRES_CONNECTION = 'POSTGRES_CONNECTION';
